name: CI
on: { push: { branches: [main] }, pull_request: { branches: [main] } }
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with: { args: "--no-progress --max-concurrency 4 ./**/*.html ./**/*.md" }
        continue-on-error: true
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@v2
        env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
